services:
  video-app:
    image: video-app:latest
    container_name: video-app
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - NUXT_DB_URL=${DB_URL}
      - NUXT_JWT_SECRET=${JWT_SECRET}
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - FFPROBE_PATH=/usr/bin/ffprobe
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
